### ISSUE TITLE
Enhance leanphp/behat-code-coverage

### ISSUE THREAD

**Issue by dannylewis-sheffield** [openbuild-sheffield/micro-api#2]
https://github.com/leanphp/behat-code-coverage could be enhanced to allow multiple reports to be generated see https://github.com/leanphp/phpspec-code-coverage

e.g.

```
    format:
      - text
      - html
      #- clover
      #- php
      #- xml
    output:
      html: coverage
      #clover: coverage.xml
      #php: coverage.php
      #xml: coverage
```

instead of single output:

```
      report:
        # report format (html, clover, php, text)
        format:    html
        # report options
        options:
          target:: build/behat-coverage/html
```

see https://github.com/leanphp/behat-code-coverage/issues/3
